name:                my-project
version:             0.1.0.0
github:              "Maickel-Hartlief/BP"
license:             BSD3
author:              "Maickel Hartlief"
maintainer:          "m.hartlief@sudent.rug.nl"
copyright:           "2020 Maickel Hartlief"

extra-source-files:
- README.md

synopsis:            Explicit and Succinct Model Checking for Public Announcement Logic.
category:            Logic

description:         See README.md.

dependencies:
- base >= 4.7 && < 5
- smcdel

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  my-project-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - my-project
    - random
    - criterion
  criterion2pgfplotcsv:
    main:               criterion2pgfplotcsv.hs
    source-dirs:        graph
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - my-project
    - split
    - scientific
    - MissingH
    - parsec

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - my-project
    - hspec
    - QuickCheck

benchmarks:
  bench-muddychildren:
     source-dirs:     app
     main:            Main.hs
     dependencies:
       - my-project
       - criterion
