name:                SucExpModelCheckers
version:             0.1.0.0
github:              "Maickel-Hartlief/SucExpModelCheckers"
license:             BSD3
author:              "Maickel Hartlief"
maintainer:          "m.hartlief@sudent.rug.nl"
copyright:           "2020 Maickel Hartlief"

extra-source-files:
- README.md

synopsis:            Explicit and Succinct Model Checking for Public Announcement Logic.
category:            Logic

description:         See README.md.

dependencies:
- base >= 4.7 && < 5
- smcdel

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  criterion2pgfplotcsv:
    main:               criterion2pgfplotcsv.hs
    source-dirs:        graph
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - SucExpModelCheckers
    - split
    - scientific
    - MissingH
    - parsec

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - SucExpModelCheckers
    - hspec
    - QuickCheck

benchmarks:
  bench-muddychildren:
     source-dirs:     bench
     main:            Main.hs
     dependencies:
       - SucExpModelCheckers
       - criterion
